/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	thingstestiov1 "github.com/solo-io/autopilot/codegen/render/api/things.test.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePaints implements PaintInterface
type FakePaints struct {
	Fake *FakeThingsV1
	ns   string
}

var paintsResource = schema.GroupVersionResource{Group: "things.test.io", Version: "v1", Resource: "paints"}

var paintsKind = schema.GroupVersionKind{Group: "things.test.io", Version: "v1", Kind: "Paint"}

// Get takes name of the paint, and returns the corresponding paint object, and an error if there is any.
func (c *FakePaints) Get(name string, options v1.GetOptions) (result *thingstestiov1.Paint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(paintsResource, c.ns, name), &thingstestiov1.Paint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*thingstestiov1.Paint), err
}

// List takes label and field selectors, and returns the list of Paints that match those selectors.
func (c *FakePaints) List(opts v1.ListOptions) (result *thingstestiov1.PaintList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(paintsResource, paintsKind, c.ns, opts), &thingstestiov1.PaintList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &thingstestiov1.PaintList{ListMeta: obj.(*thingstestiov1.PaintList).ListMeta}
	for _, item := range obj.(*thingstestiov1.PaintList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested paints.
func (c *FakePaints) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(paintsResource, c.ns, opts))

}

// Create takes the representation of a paint and creates it.  Returns the server's representation of the paint, and an error, if there is any.
func (c *FakePaints) Create(paint *thingstestiov1.Paint) (result *thingstestiov1.Paint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(paintsResource, c.ns, paint), &thingstestiov1.Paint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*thingstestiov1.Paint), err
}

// Update takes the representation of a paint and updates it. Returns the server's representation of the paint, and an error, if there is any.
func (c *FakePaints) Update(paint *thingstestiov1.Paint) (result *thingstestiov1.Paint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(paintsResource, c.ns, paint), &thingstestiov1.Paint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*thingstestiov1.Paint), err
}

// Delete takes name of the paint and deletes it. Returns an error if one occurs.
func (c *FakePaints) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(paintsResource, c.ns, name), &thingstestiov1.Paint{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePaints) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(paintsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &thingstestiov1.PaintList{})
	return err
}

// Patch applies the patch and returns the patched paint.
func (c *FakePaints) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *thingstestiov1.Paint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(paintsResource, c.ns, name, pt, data, subresources...), &thingstestiov1.Paint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*thingstestiov1.Paint), err
}
