apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: painting-app
    app.kubernetes.io/name: painting-app
  name: paints.things.test.io
spec:
  group: things.test.io
  names:
    kind: Paint
    listKind: PaintList
    plural: paints
    singular: paint
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1
    served: true
    storage: true
