// Code generated by protoc-gen-go. DO NOT EDIT.
// source: autopilot.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The AutoPilotProject file is the root configuration file for the project itself
// this file will be used to build and deploy the autopilot operator
// Loaded automatically by the autopilot CLI
// Default location is 'autopilot.yaml'
type AutoPilotProject struct {
	// the name (kubernetes Kind) of the top-level
	// CRD for the operator
	// Specified via the `ap init <Kind>` command
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// the ApiVersion of the top-level
	// CRD for the operator
	ApiVersion string `protobuf:"bytes,2,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	// Each phase represents a different
	// stage in the lifecycle of the CRD (e.g. Pending/Succeeded/Failed).
	//
	// Each phase specifies a unique name
	// and its own set of inputs and outputs.
	Phases []*Phase `protobuf:"bytes,3,rep,name=phases,proto3" json:"phases,omitempty"`
	// enable use of a Finalizer to handle object deletion
	EnableFinalizer bool `protobuf:"varint,4,opt,name=enableFinalizer,proto3" json:"enableFinalizer,omitempty"`
	// custom Parameters which extend AutoPilot's builtin types
	CustomParameters     []*Parameter `protobuf:"bytes,5,rep,name=customParameters,proto3" json:"customParameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AutoPilotProject) Reset()         { *m = AutoPilotProject{} }
func (m *AutoPilotProject) String() string { return proto.CompactTextString(m) }
func (*AutoPilotProject) ProtoMessage()    {}
func (*AutoPilotProject) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c7e86e2b87635e, []int{0}
}

func (m *AutoPilotProject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoPilotProject.Unmarshal(m, b)
}
func (m *AutoPilotProject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoPilotProject.Marshal(b, m, deterministic)
}
func (m *AutoPilotProject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoPilotProject.Merge(m, src)
}
func (m *AutoPilotProject) XXX_Size() int {
	return xxx_messageInfo_AutoPilotProject.Size(m)
}
func (m *AutoPilotProject) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoPilotProject.DiscardUnknown(m)
}

var xxx_messageInfo_AutoPilotProject proto.InternalMessageInfo

func (m *AutoPilotProject) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *AutoPilotProject) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *AutoPilotProject) GetPhases() []*Phase {
	if m != nil {
		return m.Phases
	}
	return nil
}

func (m *AutoPilotProject) GetEnableFinalizer() bool {
	if m != nil {
		return m.EnableFinalizer
	}
	return false
}

func (m *AutoPilotProject) GetCustomParameters() []*Parameter {
	if m != nil {
		return m.CustomParameters
	}
	return nil
}

// MeshProviders provide an interface to monitoring and managing a specific
// mesh.
// AutoPilot does not abstract the mesh API - AutoPilot developers must
// still reason able about Provider-specific CRDs. AutoPilot's job is to
// abstract operational concerns such as discovering control plane configuration
// and monitoring metrics.
type Phase struct {
	// name of the phase. must be unique
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// description of the phase. used for comments and docs
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// indicates whether this is the initial phase of the system.
	// exactly one phase must be the initial phase
	Initial bool `protobuf:"varint,3,opt,name=initial,proto3" json:"initial,omitempty"`
	// the set of inputs for this phase
	// the inputs will be retrieved by the scheduler
	// and passed to the worker as input parameters
	//
	// custom inputs can be defined in the
	// autopilot.yaml
	Inputs []string `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// the set of outputs for this phase
	// the inputs will be propagated to k8s storage (etcd) by the scheduler.
	//
	// custom outputs can be defined in the
	// autopilot.yaml
	Outputs              []string `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Phase) Reset()         { *m = Phase{} }
func (m *Phase) String() string { return proto.CompactTextString(m) }
func (*Phase) ProtoMessage()    {}
func (*Phase) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c7e86e2b87635e, []int{1}
}

func (m *Phase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Phase.Unmarshal(m, b)
}
func (m *Phase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Phase.Marshal(b, m, deterministic)
}
func (m *Phase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Phase.Merge(m, src)
}
func (m *Phase) XXX_Size() int {
	return xxx_messageInfo_Phase.Size(m)
}
func (m *Phase) XXX_DiscardUnknown() {
	xxx_messageInfo_Phase.DiscardUnknown(m)
}

var xxx_messageInfo_Phase proto.InternalMessageInfo

func (m *Phase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Phase) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Phase) GetInitial() bool {
	if m != nil {
		return m.Initial
	}
	return false
}

func (m *Phase) GetInputs() []string {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *Phase) GetOutputs() []string {
	if m != nil {
		return m.Outputs
	}
	return nil
}

// Custom Parameters allow code to be generated
// for inputs/outputs that are not built-in to AutoPilot.
// These types must be Kubernetes-compatible Go structs.
type Parameter struct {
	// the fully lower-case name of this resource
	// e.g. "pods", "services", "replicasets", "configmaps"
	LowerName string `protobuf:"bytes,1,opt,name=lowerName,proto3" json:"lowerName,omitempty"`
	// the singular CamelCased name of the resource
	// equivalent to Kind
	SingleName string `protobuf:"bytes,2,opt,name=singleName,proto3" json:"singleName,omitempty"`
	// the plural CamelCased name of the resource
	// equivalent to the pluralized form of Kind
	PluralName string `protobuf:"bytes,3,opt,name=pluralName,proto3" json:"pluralName,omitempty"`
	// import prefix used by generated code
	ImportPrefix string `protobuf:"bytes,4,opt,name=importPrefix,proto3" json:"importPrefix,omitempty"`
	// go package (import path) to the go struct for the resource
	Package string `protobuf:"bytes,5,opt,name=package,proto3" json:"package,omitempty"`
	// Kubernetes API group for the resource
	// e.g. "networking.istio.io"
	ApiGroup string `protobuf:"bytes,6,opt,name=apiGroup,proto3" json:"apiGroup,omitempty"`
	// indicates whether the resource is a CRD
	// if true, the Resource will be added to the operator's runtime.Scheme
	IsCrd                bool     `protobuf:"varint,7,opt,name=isCrd,proto3" json:"isCrd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Parameter) Reset()         { *m = Parameter{} }
func (m *Parameter) String() string { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()    {}
func (*Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c7e86e2b87635e, []int{2}
}

func (m *Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parameter.Unmarshal(m, b)
}
func (m *Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parameter.Marshal(b, m, deterministic)
}
func (m *Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parameter.Merge(m, src)
}
func (m *Parameter) XXX_Size() int {
	return xxx_messageInfo_Parameter.Size(m)
}
func (m *Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_Parameter proto.InternalMessageInfo

func (m *Parameter) GetLowerName() string {
	if m != nil {
		return m.LowerName
	}
	return ""
}

func (m *Parameter) GetSingleName() string {
	if m != nil {
		return m.SingleName
	}
	return ""
}

func (m *Parameter) GetPluralName() string {
	if m != nil {
		return m.PluralName
	}
	return ""
}

func (m *Parameter) GetImportPrefix() string {
	if m != nil {
		return m.ImportPrefix
	}
	return ""
}

func (m *Parameter) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *Parameter) GetApiGroup() string {
	if m != nil {
		return m.ApiGroup
	}
	return ""
}

func (m *Parameter) GetIsCrd() bool {
	if m != nil {
		return m.IsCrd
	}
	return false
}

func init() {
	proto.RegisterType((*AutoPilotProject)(nil), "autopilot.AutoPilotProject")
	proto.RegisterType((*Phase)(nil), "autopilot.Phase")
	proto.RegisterType((*Parameter)(nil), "autopilot.Parameter")
}

func init() { proto.RegisterFile("autopilot.proto", fileDescriptor_f7c7e86e2b87635e) }

var fileDescriptor_f7c7e86e2b87635e = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xdd, 0x8a, 0xd4, 0x30,
	0x14, 0xc7, 0xa9, 0x9d, 0xce, 0x6e, 0xcf, 0x0a, 0x3b, 0x84, 0x45, 0x82, 0x88, 0x94, 0x8a, 0xd0,
	0x1b, 0xa7, 0xa8, 0x2f, 0xe0, 0x07, 0xe8, 0x9d, 0x94, 0x5e, 0x78, 0xe1, 0x5d, 0xa6, 0x13, 0x67,
	0x8f, 0x9b, 0xe6, 0x84, 0x7c, 0xa8, 0xf8, 0x06, 0x3e, 0xa2, 0xe0, 0xc3, 0x48, 0x32, 0xd3, 0x76,
	0xd4, 0xbb, 0xfc, 0x7f, 0xbf, 0x36, 0xe7, 0xa3, 0x85, 0x6b, 0x11, 0x3c, 0x19, 0x54, 0xe4, 0xb7,
	0xc6, 0x92, 0x27, 0x56, 0xce, 0xa0, 0xfe, 0x9d, 0xc1, 0xe6, 0x75, 0xf0, 0xd4, 0xc5, 0xd4, 0x59,
	0xfa, 0x22, 0x07, 0xcf, 0x18, 0xac, 0xee, 0x50, 0xef, 0x79, 0x56, 0x65, 0x4d, 0xd9, 0xa7, 0x33,
	0x7b, 0x0c, 0x20, 0x0c, 0x7e, 0x94, 0xd6, 0x21, 0x69, 0x7e, 0x2f, 0x99, 0x33, 0xc2, 0x1a, 0x58,
	0x9b, 0x5b, 0xe1, 0xa4, 0xe3, 0x79, 0x95, 0x37, 0x57, 0x2f, 0x36, 0xdb, 0xa5, 0x6a, 0x17, 0x45,
	0x7f, 0xf2, 0xac, 0x81, 0x6b, 0xa9, 0xc5, 0x4e, 0xc9, 0x77, 0xa8, 0x85, 0xc2, 0x1f, 0xd2, 0xf2,
	0x55, 0x95, 0x35, 0x97, 0xfd, 0xbf, 0x98, 0xbd, 0x82, 0xcd, 0x10, 0x9c, 0xa7, 0xb1, 0x13, 0x56,
	0x8c, 0xd2, 0x4b, 0xeb, 0x78, 0x91, 0x6e, 0xbf, 0x39, 0xbf, 0x7d, 0x92, 0xfd, 0x7f, 0x4f, 0xd7,
	0x3f, 0x33, 0x28, 0x52, 0xf5, 0x38, 0x93, 0x16, 0xa3, 0x9c, 0x66, 0x8a, 0x67, 0x56, 0xc1, 0xd5,
	0x5e, 0xba, 0xc1, 0xa2, 0xf1, 0xcb, 0x50, 0xe7, 0x88, 0x71, 0xb8, 0x40, 0x8d, 0x1e, 0x85, 0xe2,
	0x79, 0xea, 0x71, 0x8a, 0xec, 0x01, 0xac, 0x51, 0x9b, 0xe0, 0x1d, 0x5f, 0x55, 0x79, 0x53, 0xf6,
	0xa7, 0x14, 0xdf, 0xa0, 0xe0, 0x93, 0x28, 0x92, 0x98, 0x62, 0xfd, 0x2b, 0x83, 0x72, 0x6e, 0x8d,
	0x3d, 0x82, 0x52, 0xd1, 0x37, 0x69, 0x3f, 0x2c, 0x4d, 0x2d, 0x20, 0x6e, 0xdb, 0xa1, 0x3e, 0x28,
	0x99, 0xf4, 0x69, 0xdb, 0x0b, 0x89, 0xde, 0xa8, 0x60, 0x85, 0x4a, 0x3e, 0x3f, 0xfa, 0x85, 0xb0,
	0x1a, 0xee, 0xe3, 0x68, 0xc8, 0xfa, 0xce, 0xca, 0xcf, 0xf8, 0x3d, 0x2d, 0xb8, 0xec, 0xff, 0x62,
	0xb1, 0x53, 0x23, 0x86, 0x3b, 0x71, 0x90, 0xbc, 0x48, 0x7a, 0x8a, 0xec, 0x21, 0x5c, 0x0a, 0x83,
	0xef, 0x2d, 0x05, 0xc3, 0xd7, 0x49, 0xcd, 0x99, 0xdd, 0x40, 0x81, 0xee, 0xad, 0xdd, 0xf3, 0x8b,
	0xb4, 0x8f, 0x63, 0x78, 0xf3, 0xf4, 0xd3, 0x93, 0x03, 0xfa, 0xdb, 0xb0, 0xdb, 0x0e, 0x34, 0xb6,
	0x8e, 0x14, 0x3d, 0x43, 0x6a, 0xe7, 0x6f, 0xd4, 0x0a, 0x83, 0xed, 0xd7, 0xe7, 0xbb, 0x75, 0xfa,
	0xff, 0x5e, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x4d, 0xcd, 0x39, 0x92, 0x02, 0x00, 0x00,
}
