// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: autopilot-operator.proto

package v1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MeshProviders provide an interface to monitoring and managing a specific
// mesh.
// AutoPilot does not abstract the mesh API - AutoPilot developers must
// still reason able about Provider-specific CRDs. AutoPilot's job is to
// abstract operational concerns such as discovering control plane configuration
// and monitoring metrics.
type MeshProvider int32

const (
	// the Operator will utilize the Service Mesh Interface (SMI) for metrics and configuration.
	// Compatible with multiple meshes (may require installation of an SMI Adapter).
	MeshProvider_SMI MeshProvider = 0
	// the Operator will utilize Istio mesh for metrics and configuration
	MeshProvider_Istio MeshProvider = 1
)

var MeshProvider_name = map[int32]string{
	0: "SMI",
	1: "Istio",
}

var MeshProvider_value = map[string]int32{
	"SMI":   0,
	"Istio": 1,
}

func (x MeshProvider) String() string {
	return proto.EnumName(MeshProvider_name, int32(x))
}

func (MeshProvider) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56f975433f2c607a, []int{0}
}

// The AutoPilotOperator file is the bootstrap
// Configuration file for the Operator.
// It is stored and mounted to the operator as a Kubernetes ConfigMap.
// The Operator will hot-reload when the configuration file changes.
// Default name is 'autopilot-operator.yaml' and should be stored in the project root.
type AutoPilotOperator struct {
	// version of the operator
	// used for reporting, metrics, etc (can be any format)
	// default is "0.0.1"
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// meshProvider determines how the operator will connect to a service mesh
	// Default is "SMI"
	MeshProvider MeshProvider `protobuf:"varint,2,opt,name=meshProvider,proto3,enum=autopilot.MeshProvider" json:"meshProvider,omitempty"`
	// workInterval to sets the interval at which CRD workers resync.
	// Default is 5s
	WorkInterval *duration.Duration `protobuf:"bytes,3,opt,name=workInterval,proto3" json:"workInterval,omitempty"`
	// Serve metrics on this address. Set to empty string to disable metrics
	// defaults to ":9090"
	MetricsAddr string `protobuf:"bytes,4,opt,name=metricsAddr,proto3" json:"metricsAddr,omitempty"`
	// Enable leader election. This will prevent more than one operator from running at a time
	// defaults to true
	EnableLeaderElection bool `protobuf:"varint,5,opt,name=enableLeaderElection,proto3" json:"enableLeaderElection,omitempty"`
	// if non-empty, watchNamespace will restrict the Operator to watching resources in a single namespace
	// if empty (default), the Operator must have Cluster-scope RBAC permissions (ClusterRole/Binding)
	WatchNamespace       string   `protobuf:"bytes,6,opt,name=watchNamespace,proto3" json:"watchNamespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoPilotOperator) Reset()         { *m = AutoPilotOperator{} }
func (m *AutoPilotOperator) String() string { return proto.CompactTextString(m) }
func (*AutoPilotOperator) ProtoMessage()    {}
func (*AutoPilotOperator) Descriptor() ([]byte, []int) {
	return fileDescriptor_56f975433f2c607a, []int{0}
}
func (m *AutoPilotOperator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoPilotOperator.Unmarshal(m, b)
}
func (m *AutoPilotOperator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoPilotOperator.Marshal(b, m, deterministic)
}
func (m *AutoPilotOperator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoPilotOperator.Merge(m, src)
}
func (m *AutoPilotOperator) XXX_Size() int {
	return xxx_messageInfo_AutoPilotOperator.Size(m)
}
func (m *AutoPilotOperator) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoPilotOperator.DiscardUnknown(m)
}

var xxx_messageInfo_AutoPilotOperator proto.InternalMessageInfo

func (m *AutoPilotOperator) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *AutoPilotOperator) GetMeshProvider() MeshProvider {
	if m != nil {
		return m.MeshProvider
	}
	return MeshProvider_SMI
}

func (m *AutoPilotOperator) GetWorkInterval() *duration.Duration {
	if m != nil {
		return m.WorkInterval
	}
	return nil
}

func (m *AutoPilotOperator) GetMetricsAddr() string {
	if m != nil {
		return m.MetricsAddr
	}
	return ""
}

func (m *AutoPilotOperator) GetEnableLeaderElection() bool {
	if m != nil {
		return m.EnableLeaderElection
	}
	return false
}

func (m *AutoPilotOperator) GetWatchNamespace() string {
	if m != nil {
		return m.WatchNamespace
	}
	return ""
}

func init() {
	proto.RegisterEnum("autopilot.MeshProvider", MeshProvider_name, MeshProvider_value)
	proto.RegisterType((*AutoPilotOperator)(nil), "autopilot.AutoPilotOperator")
}

func init() { proto.RegisterFile("autopilot-operator.proto", fileDescriptor_56f975433f2c607a) }

var fileDescriptor_56f975433f2c607a = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0xdf, 0xc2, 0x0b, 0xc8, 0x42, 0x08, 0x6e, 0x4c, 0x5c, 0x3d, 0x98, 0x06, 0xa3, 0x69,
	0x4c, 0xd8, 0x46, 0x3c, 0x1a, 0x0f, 0x18, 0x3d, 0x90, 0x88, 0x92, 0x7a, 0xf3, 0xb6, 0x6d, 0x47,
	0xd8, 0xd8, 0x76, 0x9a, 0xd9, 0x6d, 0xf9, 0x48, 0x7e, 0x4d, 0x43, 0xf9, 0x13, 0x30, 0x1e, 0x77,
	0x9e, 0x5f, 0x9e, 0xfd, 0xcd, 0x30, 0xa1, 0x0a, 0x8b, 0xb9, 0x4e, 0xd0, 0x0e, 0x31, 0x07, 0x52,
	0x16, 0x49, 0xe6, 0x84, 0x16, 0x79, 0x7b, 0x97, 0x9c, 0x5f, 0xcc, 0x11, 0xe7, 0x09, 0xf8, 0x55,
	0x10, 0x16, 0x9f, 0x7e, 0x5c, 0x90, 0xb2, 0x1a, 0xb3, 0x35, 0x3a, 0xf8, 0xae, 0xb1, 0xe3, 0x71,
	0x61, 0x71, 0xb6, 0xa2, 0xdf, 0x36, 0x35, 0x5c, 0xb0, 0x56, 0x09, 0x64, 0x34, 0x66, 0xc2, 0x71,
	0x1d, 0xaf, 0x1d, 0x6c, 0x9f, 0xfc, 0x9e, 0x75, 0x53, 0x30, 0x8b, 0x19, 0x61, 0xa9, 0x63, 0x20,
	0x51, 0x73, 0x1d, 0xaf, 0x37, 0x3a, 0x95, 0xbb, 0x1f, 0xe5, 0x74, 0x2f, 0x0e, 0x0e, 0x60, 0xfe,
	0xc0, 0xba, 0x4b, 0xa4, 0xaf, 0x49, 0x66, 0x81, 0x4a, 0x95, 0x88, 0xba, 0xeb, 0x78, 0x9d, 0xd1,
	0x99, 0x5c, 0x3b, 0xca, 0xad, 0xa3, 0x7c, 0xda, 0x38, 0x06, 0x07, 0x38, 0x77, 0x59, 0x27, 0x05,
	0x4b, 0x3a, 0x32, 0xe3, 0x38, 0x26, 0xf1, 0xbf, 0x32, 0xdb, 0x1f, 0xf1, 0x11, 0x3b, 0x81, 0x4c,
	0x85, 0x09, 0xbc, 0x80, 0x8a, 0x81, 0x9e, 0x13, 0x88, 0x56, 0x3d, 0xa2, 0xe1, 0x3a, 0xde, 0x51,
	0xf0, 0x67, 0xc6, 0xaf, 0x59, 0x6f, 0xa9, 0x6c, 0xb4, 0x78, 0x55, 0x29, 0x98, 0x5c, 0x45, 0x20,
	0x9a, 0x55, 0xf1, 0xaf, 0xe9, 0xcd, 0x80, 0x75, 0xf7, 0x57, 0xe3, 0x2d, 0x56, 0x7f, 0x9f, 0x4e,
	0xfa, 0xff, 0x78, 0x9b, 0x35, 0x26, 0xc6, 0x6a, 0xec, 0x3b, 0x8f, 0x57, 0x1f, 0x97, 0x73, 0x6d,
	0x17, 0x45, 0x28, 0x23, 0x4c, 0x7d, 0x83, 0x09, 0x0e, 0x35, 0xfa, 0xbb, 0xdb, 0xf8, 0x2a, 0xd7,
	0x7e, 0x79, 0x1b, 0x36, 0xab, 0x4d, 0xef, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xf9, 0x97,
	0x1f, 0xc2, 0x01, 0x00, 0x00,
}
