// +build !ignore_autogenerated

// Code generated by ___go_test_github_com_solo_io_autopilot_codegen_test. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Paint) DeepCopyInto(out *Paint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.PaintStatus.DeepCopyInto(&out.PaintStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Paint.
func (in *Paint) DeepCopy() *Paint {
	if in == nil {
		return nil
	}
	out := new(Paint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Paint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaintColor) DeepCopyInto(out *PaintColor) {
	*out = *in
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaintColor.
func (in *PaintColor) DeepCopy() *PaintColor {
	if in == nil {
		return nil
	}
	out := new(PaintColor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaintList) DeepCopyInto(out *PaintList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Paint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaintList.
func (in *PaintList) DeepCopy() *PaintList {
	if in == nil {
		return nil
	}
	out := new(PaintList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PaintList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaintStatus) DeepCopyInto(out *PaintStatus) {
	*out = *in
	in.TubeStatus.DeepCopyInto(&out.TubeStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaintStatus.
func (in *PaintStatus) DeepCopy() *PaintStatus {
	if in == nil {
		return nil
	}
	out := new(PaintStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TubeStatus) DeepCopyInto(out *TubeStatus) {
	*out = *in
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TubeStatus.
func (in *TubeStatus) DeepCopy() *TubeStatus {
	if in == nil {
		return nil
	}
	out := new(TubeStatus)
	in.DeepCopyInto(out)
	return out
}
