package codegen

// this header will be prepended to generated files.
// does not affect files that are explicitly modified by the user (spec.go, worker.go)
var GeneratedHeaderContent = `// Code generated by AutoPilot. DO NOT EDIT.

`