// +build !ignore_autogenerated

// Code generated by autopilot. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Quarantine) DeepCopyInto(out *Quarantine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Quarantine.
func (in *Quarantine) DeepCopy() *Quarantine {
	if in == nil {
		return nil
	}
	out := new(Quarantine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Quarantine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuarantineList) DeepCopyInto(out *QuarantineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Quarantine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuarantineList.
func (in *QuarantineList) DeepCopy() *QuarantineList {
	if in == nil {
		return nil
	}
	out := new(QuarantineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuarantineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuarantineSpec) DeepCopyInto(out *QuarantineSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuarantineSpec.
func (in *QuarantineSpec) DeepCopy() *QuarantineSpec {
	if in == nil {
		return nil
	}
	out := new(QuarantineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuarantineStatus) DeepCopyInto(out *QuarantineStatus) {
	*out = *in
	out.QuarantineStatusInfo = in.QuarantineStatusInfo
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuarantineStatus.
func (in *QuarantineStatus) DeepCopy() *QuarantineStatus {
	if in == nil {
		return nil
	}
	out := new(QuarantineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuarantineStatusInfo) DeepCopyInto(out *QuarantineStatusInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuarantineStatusInfo.
func (in *QuarantineStatusInfo) DeepCopy() *QuarantineStatusInfo {
	if in == nil {
		return nil
	}
	out := new(QuarantineStatusInfo)
	in.DeepCopyInto(out)
	return out
}
