/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/solo-io/autopilot/codegen/render/api/things.test.io/v1"
	scheme "github.com/solo-io/autopilot/codegen/render/api/things.test.io/v1/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PaintsGetter has a method to return a PaintInterface.
// A group's client should implement this interface.
type PaintsGetter interface {
	Paints(namespace string) PaintInterface
}

// PaintInterface has methods to work with Paint resources.
type PaintInterface interface {
	Create(*v1.Paint) (*v1.Paint, error)
	Update(*v1.Paint) (*v1.Paint, error)
	UpdateStatus(*v1.Paint) (*v1.Paint, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Paint, error)
	List(opts metav1.ListOptions) (*v1.PaintList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Paint, err error)
	PaintExpansion
}

// paints implements PaintInterface
type paints struct {
	client rest.Interface
	ns     string
}

// newPaints returns a Paints
func newPaints(c *ThingsV1Client, namespace string) *paints {
	return &paints{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the paint, and returns the corresponding paint object, and an error if there is any.
func (c *paints) Get(name string, options metav1.GetOptions) (result *v1.Paint, err error) {
	result = &v1.Paint{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("paints").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Paints that match those selectors.
func (c *paints) List(opts metav1.ListOptions) (result *v1.PaintList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.PaintList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("paints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested paints.
func (c *paints) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("paints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a paint and creates it.  Returns the server's representation of the paint, and an error, if there is any.
func (c *paints) Create(paint *v1.Paint) (result *v1.Paint, err error) {
	result = &v1.Paint{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("paints").
		Body(paint).
		Do().
		Into(result)
	return
}

// Update takes the representation of a paint and updates it. Returns the server's representation of the paint, and an error, if there is any.
func (c *paints) Update(paint *v1.Paint) (result *v1.Paint, err error) {
	result = &v1.Paint{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("paints").
		Name(paint.Name).
		Body(paint).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *paints) UpdateStatus(paint *v1.Paint) (result *v1.Paint, err error) {
	result = &v1.Paint{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("paints").
		Name(paint.Name).
		SubResource("status").
		Body(paint).
		Do().
		Into(result)
	return
}

// Delete takes name of the paint and deletes it. Returns an error if one occurs.
func (c *paints) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("paints").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *paints) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("paints").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched paint.
func (c *paints) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Paint, err error) {
	result = &v1.Paint{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("paints").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
